blank_issues_enabled: false
contact_links:
  - name: Question or support
    url: https://github.com/theriddleofenigma/laravel-model-validation/discussions
    about: Please ask and answer usage questions in Discussions.
